### ISSUE TITLE
sonoff rf bridge r2 can't work when  internet connection problem

### ISSUE THREAD

**Issue by smallpan0421** [AlexxIT/SonoffLAN#1127]
sonoff rf bridge r2 can't use when internet connection problem. I found when  internet can't use (wlan), sonoff rf bridege blue led will flash . The Single State Sensor/PIR Sensor can't work on home assistant.  Can I use it without internet?

**Comment by Hunter32R** [comment]
i have the same problem

**Comment by setterlee** [comment]
Same problem here… actually I’m thinking that right now there is an issue with the eWeLink servers because my rf bridge is connected to internet, I validate that on my router checking that the devide have internet connection but the eWeLink app still says that is offline…

y changed the HA component to use only local connection and HA still see the device unavailable

**Comment by AlexxIT** [comment]
If your model with your firmware can't work locally, integration can't do anything about it.

I don't know why some firmwares can work locally, and some don't.

Diagnostics above shows that device works only via cloud.

You can try to flash your device via ESPHome.
