### ISSUE TITLE
Power usage not updating reliably after update to Home Assistant 2024.3.0

### ISSUE THREAD

**Issue by dockSquadron** [AlexxIT/SonoffLAN#1358]
Power usage not updating regularly after updating Home Assistant to 2024.3.0. Was working properly in 2024.2.1. Seemed to update on a reload of the integration, and maybe sporadically.

**Comment by pilurizzu** [comment]
Me too

**Comment by spanzetta** [comment]
Me too

**Comment by dockSquadron** [comment]
I did a full reboot of the PC and it seems to be working better now.

**Comment by amaisano** [comment]
Same. I noticed this many months ago. The solution for me has been going into the eweLink IOS app and manually toggling settings or power state on/off for the plugs. Doing this seems to jog the plug power consumption state, but the problem returned a few hours later.

Note that this might be flakiness on the sonoff/coolkit.cc/ewelink side, since the 1st part IOS app was also incorrectly showing power consumption (it was stuck on 22w even though the device was powered off).

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#sonoff-pow

**Comment by amaisano** [comment]
Here are my diagnostics:
[sonoff-513c5dffce155fb2397773d228ec7529-Z906-f1d4d73feadf6253d591c547e4d4cde5.json](https://github.com/AlexxIT/SonoffLAN/files/14576938/sonoff-513c5dffce155fb2397773d228ec7529-Z906-f1d4d73feadf6253d591c547e4d4cde5.json)

**Comment by Opontios** [comment]
@dockSquadron
@amaisano
Have you ever red the docs and added the corresponding lines to the sonoff.yaml?
```
sonoff:
  devices:
    1000xxxxxx:
      reporting:
        energy: [3600, 10]  # update interval (seconds), history size (days)
```

**Comment by amaisano** [comment]
For me, I've never touched the the YAML for Sonoff, because it was always 100% working plug-and-play with the integration from day 1. Until now. So I haven't needed to go through the docs at all.

I can try doing that now, but I'm not sure why I would need to suddenly when it's been fine for months. Maybe it's the newer firmware for my `S31TPB(US)` plugs?

**Comment by Opontios** [comment]
> For me, I've never touched the the YAML for Sonoff, because it was always 100% working plug-and-play with the integration from day 1. Until now. So I haven't needed to go through the docs at all.
> 
> I can try doing that now, but I'm not sure why I would need to suddenly when it's been fine for months. Maybe it's the newer firmware for my `S31TPB(US)` plugs?

It was always in the docs, so there was a reason why the developer of the integration had put it there. I guess that you don't realize that whether it reports or not doesn't depend on the particular integration, but on the way the ewelink software works. So, if anything has changed, it was not in the integration, but on the ewelink side. The developer can correct me if I'm wrong

**Comment by AlexxIT** [comment]
@amaisano You need to collect more logs. Not just few start seconds. Maybe 10 minutes.

**Comment by amaisano** [comment]
I understand. Unfortunately I found a quick fix so I won't be debugging anytime soon. I switched the device configurations from "Auto" to "Cloud" and the problems I was experiencing went away completely.

If the problem comes back again I will def. work on more logging, but for now I am good. Busy, you know? Thank you for the help though.

**Comment by Opontios** [comment]
> I understand. Unfortunately I found a quick fix so I won't be debugging anytime soon. I switched the device configurations from "Auto" to "Cloud" and the problems I was experiencing went away completely.
> 
> If the problem comes back again I will def. work on more logging, but for now I am good. Busy, you know? Thank you for the help though.

Right, because now the only communication you have with sonoff devices is through the cloud, so it's polling anyway, but you loose the beauty of local control, you will be dependent on the internet.
