### ISSUE TITLE
Switch Not Working

### ISSUE THREAD

**Issue by milandzuris** [AlexxIT/SonoffLAN#1364]
Device Stop Working, ON/OFF for my Switch T1 2C not work im click turn on or off nothing make, only help me reload integration but after few minutes same problem, have problem only with this switch, logs clear.

**Comment by litecross91** [comment]
Same with M5 switches.
https://github.com/AlexxIT/SonoffLAN/issues/1368

**Comment by petebanham** [comment]
I have the same issue, just seems to be with my 2 gang/channel switches, the singles all still work.  Operating the switch in HA has no effect on the light and the switch then flicks back to previous state in HA.  Re loading the integration fixed it but only for a few hours. Mahjong on all 3 of my TX2Cs and my NSpanel, but all single switches and swart plugs are fine

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by petebanham** [comment]
1. Check the number of online devices on the System Health page
  _It shows 13/16.  The 3 that are offline as not currently being used and are indeed offline_
2. Check warning and errors on the Logs page
 _Nothing in the main HA logs_
3. Check debug logs on the Debug page (must be enabled in integration options)
  _That page looks okay to me, no errors, but can share if needed. Will re check it next time it happens_
4. Check open and closed issues
  _Added to this existing issue as looks to be the  same to me_ 
5. Share integration diagnostics (supported from Hass v2022.2):
 _Unfortunately I can't seem to download diagnostic data from any integration, HA gives me an "unknown Network error" when I try so I will need to try and troubleshoot that._
Thanks

**Comment by petebanham** [comment]
Have just noticed that the issue has recurred for me. There are no new entries on the debug log page (I haven't restarted the integration yet)  ot the main HA logs.  I still cant download the diag info but I have double checked all my devices and everything still works from Alexa or eWelink  but in HA  4 of my 5 2 gang/channel switches have stopped responding,. The issue is affecting my NSpanel and 3 of my 4 T0 2 channel switches (all 4 are on the same firmware version) . Interestingly  the one that is still working is the only one that does not have a lighting load attached to it as it is being  used as a 2 way switch, triggering automations to control other switches . I can't see how the lack of load would make any difference to this  integration but thought it was worth noting.

**Comment by petebanham** [comment]
[config_entry-sonoff-ccd185cabb653f722dbcc8c75f404e60.json](https://github.com/AlexxIT/SonoffLAN/files/14920913/config_entry-sonoff-ccd185cabb653f722dbcc8c75f404e60.json)

Managed to get the diag info from a different  HA client, it is attached. Thanks

**Comment by petebanham** [comment]
Does anyone  have any ideas on  this please as the switches still stop working  a couple of times a day?

**Comment by AlexxIT** [comment]
@petebanham you have attached whole integration diagnostics. With which device you have problems?

**Comment by petebanham** [comment]
The TX2Cs and the NSpanel. I can separate those out if it helps?

**Comment by AlexxIT** [comment]
You have latest integration version. All of your devices works locally. I don't know what the problem could be related to.

**Comment by petebanham** [comment]
Yes its strange that it is only the 2 channel switches that  are affected.  An integration reload fixes it but only for a few hours  :-(

**Comment by petebanham** [comment]
I have noticed that reloading the specific device rather than the whole integration also gets the switch working again so as a temp work around I have set up a automation that reloads all the dual channel switches once  an hour so I should now have a maximum outage time of just under an hour.  Not ideal though......

**Comment by MohamedIsmailelkholy** [comment]
Same problem here with 2 gang switches and ns panel

**Comment by petebanham** [comment]
I am still having this issue and need to reload the entries every few hours ☹️

**Comment by AlexxIT** [comment]
This is same https://github.com/AlexxIT/SonoffLAN/issues/1368
