### ISSUE TITLE
[Feature Request] RFBridge buttons should update the state as well

### ISSUE THREAD

**Issue by Steeven9** [AlexxIT/SonoffLAN#1395]
I have a 433MHz remote registered via an RFBridge, and all the buttons get picked up as buttons in Homeassistant. Perfect.

However, I randomly discovered that the state of those buttons is not updated when they are triggered, only the `last_triggered` attribute. However, if I trigger the button in Homassistant manually, only the state updates, leading to the two attributes having different values.

Furthermore, on reboot the `last_triggered` attribute is not persisted, while the state is. Another advantage of syncing the two would be to have the correct value after a reboot.

![image](https://github.com/AlexxIT/SonoffLAN/assets/25285679/11951a41-d909-4bfb-bd67-154afa65657d)

**Comment by AlexxIT** [comment]
Looks like it's default Hass button behaviour:
https://github.com/home-assistant/core/blob/58c7a97149c36f89657b7785b7abc326e81e12ca/homeassistant/components/button/__init__.py#L89

The button component has a very strange design. I don't want to change anything here because it could be broken in future Hass updates.
