### ISSUE TITLE
working locally with devices not on ewelink account

### ISSUE THREAD

**Issue by javifly** [AlexxIT/SonoffLAN#1503]
This extension works locally with ewelink devices. On this basis you can do the following:

1. View all the devices in the local network even if they are not associated to your ewelink? account.

2. Without having an ewelink account you can see the devices in the local network?

thank you

**Comment by 3jam3** [comment]
Without an eWeLink account, LAN mode does not exist. Well, how else can you connect devices with original Sonoff firmware to the network? In short: When you connect them and then delete the account, they remain on the network but no communication takes place. The important element here seems to be the eWeLink app, which requires an account to be added in order to start "talking" to the devices at all.
I once tested this myself with the described result.

**Comment by AlexxIT** [comment]
I didn't really understand the question.

**Comment by javifly** [comment]
This extension works locally with ewelink devices. On this basis you can ask the following questions.

Does this software allow you to see all the devices in the local network even if they are not associated to your ewelink account?
Example: In my home network there are sonoff devices associated to my wife's account, others to my own account and others to my son's. With this software can I see all the devices and control them without adding my wife's and my son's account because they are all in local network?

Without having an ewelink account can you see the devices on the local network?
Example: In my home network there are sonoff devices associated to my wife's account, others to my own account and others to my son's. With this software can I see all the devices and control them without adding any ewelink account because they are all in local network?

thanks

Translated with DeepL.com (free version)

**Comment by 3jam3** [comment]
The answers are short: No, it doesn't and no, you cannot.

**Comment by javifly** [comment]
thanks!

**Comment by AlexxIT** [comment]
ewelink devices are protected by a local encryption key. The key is different for each device.
The key can be fetched from the cloud, using the owner's account.
