### ISSUE TITLE
Reading of state

### ISSUE THREAD

**Issue by JiriKursky** [AlexxIT/SonoffLAN#344]
Hello, I have issue with state of switch.
I am talking about default mode "cloud - local".
Everything work well if you do not use that frequently turn_on/turn_off. In some cases it stops to read real state of device.
I have about 9 devices.
If I use service turn_on, turn_off via HA service - it works but state is wrong and it is not possible to control that via standard switch.py

How I was investigated in your code system suddenly stops calling proc _zeroconf_handler in module sonoff_local.py and therefore switch.py is receiving wrong info about state.
As I saw they made some changes and changed ServiceBrowser to HaServiceBrowser and others imports. Maybe it is root case.

Kind regards, Jiri

**Comment by partneroid-zz** [comment]
Not sure if related but how one exactly reads the status of a switch when in cloud mode? IMHO should be able to disable HA side when either cloud or the switch is unreachable, an equivalent for availability option for MQTT as an example, payload_available / payload_not_available. This also allows generating alerts should the switch go unreachable due to malfunction or similar reason.

**Comment by AlexxIT** [comment]
@JiriKursky it's very strange, because if you have problem with local mode - than cloud mode should work.

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
