### ISSUE TITLE
Cloud mode cannot work simultaneously with two copies of component - but I don't have 2 copies (I think!)

### ISSUE THREAD

**Issue by thisisbenwoo** [AlexxIT/SonoffLAN#347]
Hi,

I'm getting multiple entries with the following error in HA:

> ### Sonoff Warning
> Cloud mode cannot work simultaneously with two copies of component. Read more: https://github.com/AlexxIT/SonoffLAN#config-examples
> 

But, as far as I know, I do NOT have 2 copies of the component. Furthermore, I was using the exact same config just fine until the latest HA update or the Integration Update (not sure which one resulted in breaking the config).

My configuration.yaml has the following entry:
`sonoff: !include sonoff.yaml`

In my sonoff.yaml, I have the following:
```
username: !secret email
password: !secret sonoff_password
force_update: [temperature, power]
sensors: [temperature, humidity, power, current, voltage, rssi]
default_class: light # (optional), default switch
```

I have 3 devices - 2x Sonoff Micros (TV bias lights) and a Sonoff Basic R2 (for the fireplace lights). When I do a search for "sonoff" in my entities, I get the following:

![image](https://user-images.githubusercontent.com/45885373/104253865-6680aa80-542a-11eb-8887-02db67c56148.png)

So, I don't see how/where I might have 2 copies of the component. 
Thanks in advance for your help. 

Ben

**Comment by thisisbenwoo** [comment]
BTW, I removed `switch.sonoff_fireplace`, but it made no difference.

**Comment by AlexxIT** [comment]
Working mobile app or another service with same ewelink account - it is also "second copy"

**Comment by guaro2k** [comment]
Can I turn off this message then? I want to keep using the mobile app because its what I use to set up new devices. Eventually I move to HA but still, I can't just log off from the main app in my phone

**Comment by thisisbenwoo** [comment]
Thanks @AlexxIT, I don't know what I did, but it actually somehow resolved itself! I still see the devices in the eWeLink app, but for some unexplained reason, it is working!

**Comment by AlexxIT** [comment]
Go to link to documentation in this message. You should create second account and share devices to it.
You shouldn't ignore the message. Your connection to cloud breaks constantly.

**Comment by thisisbenwoo** [comment]
OK. I'll do that.. thanks!

---
*BenWoo* | +1 (212) 724-1188 | *this*is*ben*woo@gmail.com

**Comment by SdeGeata** [comment]
> #AlexIT:
>Go to link to documentation in this message. You should create second account and share devices to it.
>You shouldn't ignore the message. Your connection to cloud breaks constantly.

I've been getting the same error since my last, extremely painful Home Assistant upgrade. How do you mean second account and share devices to it???

**Comment by AlexxIT** [comment]
Create two ewelink accounts

**Comment by gideonklein** [comment]
Good morning, I have the same problem but I have 2 sonoff account. In the second account I shared all devices and I use this sonoff account in home assistant. I am connected by my mobil phone only in the principal account (with different email and password). How is possible I continue to have the same alert? I checked the sonoff.json and the saw 2 time the email of the principal account ("sharedBy":{"email":"xxxxxxxx@gmail)

**Comment by AlexxIT** [comment]
Maybe you use second account somewhere else?

**Comment by SdeGeata** [comment]
I couldn't figure out this "second account" thing, nor where the issue was coming from in the first place. I ended up turning off the internet access for all my Sonoff devices from my Home Assistant config, only using it locally. I really don't need to access the devices from outside my LAN anyway, as Home Assistant does it all anyhow locally - and if I really needed to, I can still manually turn on/off everything through Home Assistant, which I can access outside the LAN.

   As soon as I configured the Sonoff module for LAN only, the alerts went away. No problems at all with any of the functionality. Hope that helps.


Here's my Home Assistant entry from the configuration.yaml:

`sonoff:
  username: stiofan.degeata@myemail.com
  password: !secret sonoff
  mode: local
  reload: always`

**Comment by gideonklein** [comment]
Thanks for the replies. I did all the possible tests and I understood the problem: I installed the app on my mobile phone and I always keep Home Assistant open on my pc. In order not to have conflicts, therefore, I have to disconnect from the APP if I want to work on the PC and vice versa. Unfortunately I cannot set the "local" mode because I have leds and bridges devices that do not support local but only the cloud. Is there a way to be able to access the home assistant both on the pc and wit mobile phone app simultaneously? I have a tablet installed on the wall with the App but I disconnected it. If I understood there are no way to have remote home assistant if I am out of home if I don disconnect app on tablet and close pc. Thanks anyway

**Comment by SdeGeata** [comment]
Hello @gideonklein;

   I see your dilemma. It would seem in your situation, the solution that worked for me doesn't help you. I guess the best solution for you is the "second account" option.

  Best of luck!

**Comment by AlexxIT** [comment]
You need use one ewelink account for mobile, second for home assistant, third for another place of you need, etc.

**Comment by gideonklein** [comment]
Dear @SdeGeata and @AlexxIT

thank you for your help. I tried in local mode and everything works very well (more fast end without warning messages) except the L1 led and consumption (sonoff.update_consumption). I have 70 Sonoff devices and only one led L1 so I can give up on it (I will use only a strip led with Shelly RGBW). But there is a way to have consumption Sonoff Pow?
About ewelink account, my problem is different.
- I have first account that I open sometime only if I have to add other devices or for some setting because I use home assistant and not ewelink.
- I have the second account where are shared all devices from the first account and it is always disconnected from my mobil phone or my tablet. Never I use this ewelink account I use it only for home assistant.
But the problem is this: If I open home assistant in my pc and then I open home assistant (official app home assistant) with my phone or tablet there is conflict. How I can open Home assistant with different ewelink account? Maybe I can set 2 different ewelink user and password in the configuration.yaml? Like this?:
sonoff:
  username: usernameA
  password: passwordA
sonoff2:
  username: usernameB
  password: passwordB

Thank you so much for your time

**Comment by AlexxIT** [comment]
@gideonklein open two web interfaces of one Home Assistant should not create this problem
