### ISSUE TITLE
.sonoff.json Not Generating

### ISSUE THREAD

**Issue by ncodee** [AlexxIT/SonoffLAN#378]
Hi, I've tried everything to get the `.sonoff.json` file to generate so I can use the online mode, however, I tried every method and it still doesn't work. At the moment I am using the Local method with the device key, which works fine, but I'd like to use the online mode.

Could someone kindly send an example of their`.sonoff.json` file (blanking private info), so I could take a look into it?

Thanks

**Comment by sany3001** [comment]
> Hi, I've tried everything to get the `.sonoff.json` file to generate so I can use the online mode, however, I tried every method and it still doesn't work. At the moment I am using the Local method with the device key, which works fine, but I'd like to use the online mode.
> 
> Could someone kindly send an example of their`.sonoff.json` file (blanking private info), so I could take a look into it?
> 
> Thanks

I have similar problem. All is setup from my side, I have created new eWeLink account in eWeLink Android app, shared some of my devices with this new account. Using this account in /config/configuration.yaml.

`sonoff:
  username: email
  password: password
  reload: always
  
logger:
  default: info
  logs:
    custom_components.hacs: debug
    hacs: debug
    queueman: debug
    AIOGitHubAPI: debug`

I even don't know where to see log activated above. This could help maybe.

**Comment by ncodee** [comment]
> `sonoff:
> username: email
> password: password
> reload: always
> 
> logger:
> default: info
> logs:
> custom_components.hacs: debug
> hacs: debug
> queueman: debug
> AIOGitHubAPI: debug`
> 
> I even don't know where to see log activated above. This could help maybe.

Hey, thanks for replying, is this your `.sonoff.json` file?

**Comment by sany3001** [comment]
That code snippet above is from /config/configuration.yaml file.
In my case the problem was wrong password. Actually it was character that was blocking login to SonOff servers.
So I changed my password to contain only numbers and letters.

What helped me discover my problem was activation of debug:

`sonoff:
  username: mail
  password: password
  reload: always
#  mode: cloud #cloud only mode
  debug: True 
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage, rssi]
`

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
