### ISSUE TITLE
Support for Sonoff RE5V1C 

### ISSUE THREAD

**Issue by crozo5** [AlexxIT/SonoffLAN#39]
It would be awesome with [Sonoff RE5V1C](https://www.itead.cc/sonoff-re5v1c.html)

**Comment by AlexxIT** [comment]
Do you have? Does not work? What version of firmware?

**Comment by crozo5** [comment]
> Do you have? Does not work? What version of firmware?


I bought it but it still hasn't arrived. When the sonoff arrives I will try it and tell you if it works

**Comment by AlexxIT** [comment]
@crozo5 arrived? :)

**Comment by yusrimathews** [comment]
@AlexxIT can we reopen this issue? I have the RE5V1C with firmware 3.5.1

**Comment by AlexxIT** [comment]
@yusrimathews have you problems with it?

**Comment by yusrimathews** [comment]
> @yusrimathews have you problems with it?

Yes - I've paired it with the eWelink app but it doesn't show up in home assistant.

**Comment by AlexxIT** [comment]
@yusrimathews show your config. Did you reboot Hass after adding the device?

**Comment by yusrimathews** [comment]
I paired it with the eWelink app, and restarted Hass but still no switch.

Config:
```
sonoff:
    username: *****
    password: *****
    reload: always
```

**Comment by AlexxIT** [comment]
You can enable debug logs and check there

**Comment by yusrimathews** [comment]
Thanks @AlexxIT - turns out I needed to retrieve the device key and list the device in config.

**Comment by AlexxIT** [comment]
It's strange. Because with your config all should be done automatically.

**Comment by yusrimathews** [comment]
Yes, agreed. This happened because I have multiple eWelink accounts, sharing my devices across them.

The RE5V1C wasn't shared with the credentials I was using with Hass, but the local mode still seemed to identify the device on the LAN stating it requires the device key, and when I specifically set the device key, it then worked.

I then realised the device needed to be shared with the Hass credentials - the multiple eWelink accounts through me off, I wish they could just sort their sessions. I am now using the same config I had initially, and it's all working as expected.
