### ISSUE TITLE
Not all devices are detected.

### ISSUE THREAD

**Issue by elusivestudio** [AlexxIT/SonoffLAN#536]
I have several Sonoff devices in my house, but not all are detected via Hassio. Is this a known issue or there is a workaround?

**Comment by Gferretta** [comment]
Hi
A few days ago my TH16 v3.5.0 suddenly went offline.
There is no way to get it recognized again.
I changed my WiFi, my ewelink app account, etc.
It always adds it to my account, but it goes OFFLINE immediately.
I'm sure it's a general problem and not mine, since the rest of the sonoff works well, and as I read in other groups, the same thing is happening to many.
And to finish affirming my opinion, I have other THs with old firmware and until that moment, I was proposing the upgrade to v3.5.0, and now v3.4.1 appears as the last one available.

I have made the claim in iTead and we are exchanging opinions and videos, but for now that TH is unusable.

**Comment by AlexxIT** [comment]
@Gferretta the go offline in ewelink app?

**Comment by AlexxIT** [comment]
@elusivestudio all devices from readme page should supported

**Comment by Gferretta** [comment]
> @Gferretta they go offline in ewelink app?

In ewelink app appears OFFLINE and TH16 lights blinking
Delete it from my account and pair, but always add good but remain OFFLINE

Obviously, idem in HA.

For me exist a big trouble with Sonoff Servers.

Look (5 years ago and same problem)
[Can't Pair Sonoff TH16's](https://support.itead.cc/support/discussions/topics/11000007440)

**Comment by AlexxIT** [comment]
You may flash device with ESPHome

**Comment by Gferretta** [comment]
> You may flash device with ESPHome

Hi Alex
Sorry for the OT
If it is not too much trouble for you, is there any possibility of consulting you by mail or private, about my problem with this TH16?
I can show you the videos that I sent to iTead, and there decide if I should flash and with what firmware (Tasmota, ESPHome, etc)
I never did, so I was using your integration to use the original firmware.

Regards and thanks

**Comment by AlexxIT** [comment]
@Gferretta you can contact to me in Telegram with same nick name

**Comment by AlexxIT** [comment]
Closed because no response
