### ISSUE TITLE
Sonoff NSPanel

### ISSUE THREAD

**Issue by cfgroenewald** [AlexxIT/SonoffLAN#688]
Hi Alex 

how do I use the new NS panel with your integration?

**Comment by DavidFFerreira** [comment]
I would like to have it too before flash tasmota on it

**Comment by kenge1967** [comment]
I would like to have it too instead of flashing it

**Comment by AlexxIT** [comment]
A very expensive device to buy for experiments

**Comment by bwp91** [comment]
Example params i have here:
https://github.com/bwp91/homebridge-ewelink/blob/a6c1456c35a8f05deea46c6c5d71d91246fbbade/lib/device/panel.js#L114

The `switches` correspond to the two physical buttons. The only other param I use is `temperature`.

Maybe this helps :)

**Comment by AlexxIT** [comment]
What is the uiid of the device?

**Comment by bwp91** [comment]
133

**Comment by zanna1972** [comment]
Hi, I have just installed SonoffLan to control my NSPanel EU.
4 entities recognized: two of them are the physical buttons and are ok, the others I don't understand...
There isn't an entity corresponding to the temperature sensor... how I can add it manually? 
And finally, there isn't the entity corresponding to the set point for starting heating.
I bought the nspanel because it's a thermostat, but at this moment, in HA I can use it only as a light switch.
Do you have a roadmap to add those functionalities?

**Comment by AlexxIT** [comment]
Some users with this panel in this issue #751

**Comment by AlexxIT** [comment]
As I know this device can't be shared with another account:
https://github.com/AlexxIT/SonoffLAN/issues/751#issuecomment-1107518399

So someone needs to create temporary ewelink account with this device and send its credentials to me.

**Comment by AlexxIT** [comment]
Thermostat for NS Panel added to latest master-version

**Comment by DavidFFerreira** [comment]
NSPanel now dont show humidity only temp and outside temp?!? What is the outside temp? new sensor?

**Comment by DavidFFerreira** [comment]
@AlexxIT

**Comment by AlexxIT** [comment]
NSPanel don't have humidity sensor
