### ISSUE TITLE
Battery voltages shown as percentages

### ISSUE THREAD

**Issue by tescophil** [AlexxIT/SonoffLAN#801]
In the latest version 3.0.1 various attributes for switches/sensors etc, have been broken out into separate entities.

In the case of the DW2 Door/Window sensor, the battery voltage which was previously an attribute of the sensor is now a separate battery entity. However, the voltage of the battery is represented as a percentage in the entity. This means that the battery is always shown at a critical level (as it is always less than 3%)

**Comment by AlexxIT** [comment]
Duplicate #798

**Comment by tescophil** [comment]
Apologies, did not see the other issue.

**Comment by rcarnevalli** [comment]
Hi, 
I use the battery voltage value on my dashboard and the solution that includes the binary sensor overrode the other with the voltage that now just shows as unavailable. The fix is ​​very simple, just change the "%" to "Vdc", nothing more! I would like to continue using voltage as a reference. Thanks!

**Comment by AlexxIT** [comment]
#808
