### ISSUE TITLE
cant update the new password

### ISSUE THREAD

**Issue by tammeryousef1006** [AlexxIT/SonoffLAN#878]
Hello Alex 

after changing the current password at ewelink account , im unable to update the password at home assistant sonoff integration without deleting the integration (to not lose customizations and automations)

**Comment by kingtheydon** [comment]
@tammeryousef1006 I have this same issue (reset ewelink password).  Are you saying you can delete the integration, restart, then reinstall and you can input the new info correctly?

I just get a "This account is already configured" message constantly

**Comment by tammeryousef1006** [comment]
Yes exactly

**Comment by tammeryousef1006** [comment]
i can delete the integration and restart then add the account with the new password , but this will make me lose all the customized configuration related from all over again

**Comment by kingtheydon** [comment]
> i can delete the integration and restart then add the account with the new password , but this will make me lose all the customized configuration related from all over again

Yeah thats what I found.  Luckily not a big deal for me as I do not have many customized configurations. 

Since playing with this sonoff integration I actually purchased/tried the usb 3.0 sonoff dongle, and that works fine without any of ewelink stuff. Can use the ZHA add on fine.

Seems this may only be an "issue" when using the Sonoff ZB Bridge hub and this integration.

**Comment by AlexxIT** [comment]
Try latest release v3.1.0. Maybe it helps

**Comment by sgbossinga** [comment]
I have the same problem "This account is already configured"

**Comment by andreprandina** [comment]
Same here. After message from HA to reconfigure integration it keeps saying it's already configured. I have about 25 devices connected. I really need a better solution than just uninstall and install everything again.

**Comment by Mattyfaz** [comment]
Stuck unable to reconfigure it as well :(

**Comment by BatmanKuhn** [comment]
I have similar issues.
- Using 3.1.0
- Removed old sonoff section from configuraion.yaml file
- Getting two errors:
  
![3](https://user-images.githubusercontent.com/20957380/177935895-a16e7b69-3809-4bbc-a6a4-0f70c58be808.png)
![1](https://user-images.githubusercontent.com/20957380/177935899-04b71388-6a19-4ffc-bcec-094ab89f084d.png)
![2](https://user-images.githubusercontent.com/20957380/177935901-6b4cb970-27c8-42b9-9962-41334053e96e.png)

And i cannot use the Sonoff L1 (LED Strip) unavailable.
Any ideas?

**Comment by sgbossinga** [comment]
> I have similar issues.
> 
> * Using 3.1.0
> * Removed old sonoff section from configuraion.yaml file
> * Getting two errors:
> 
> ![3](https://user-images.githubusercontent.com/20957380/177935895-a16e7b69-3809-4bbc-a6a4-0f70c58be808.png) ![1](https://user-images.githubusercontent.com/20957380/177935899-04b71388-6a19-4ffc-bcec-094ab89f084d.png) ![2](https://user-images.githubusercontent.com/20957380/177935901-6b4cb970-27c8-42b9-9962-41334053e96e.png)
> 
> And i cannot use the Sonoff L1 (LED Strip) unavailable. Any ideas?

I have exactly the same problem/errors and also removed the old config in configuratioin.yaml. I have only S26 switches and they all work fine auto mode. Probably in local mode now.

**Comment by BatmanKuhn** [comment]
After upgrading to 2022.7.1 my LED strip works again. However still getting the same Sonoff errors as mentioned above.

**Comment by NeeeeB** [comment]
Same problem here too after upgrading to 2022.7.1...
It says I need to reconfigure (although I haven't changed anything, including password), and when I hit the reconfigure button and enter credentials, it says it is already configured...
@AlexxIT any comment on this ?

**Comment by JeandreCloete** [comment]
Hi everyone and Alexxx,
I started experiencing the same earlier this week. No new devices add, no password updated, and all of a sudden the integration needed reconfiguration, but doesn't allow the update with the above message.
I in fact did delete it and re-added it, it would only add without the password.
All my devices was reset (i have 62 sonoffs...so that was fun...hahaha) However, only the LAN devices are lets say functional within HA. All the other devices remain unavailable. In one or two instances, the show online, but as soon as a action is performed on them they go into unavailable again.
Please help...there are no errors that I could see in any of the logs. Also, I have done all the updates....still this persists....

This is a SONOFF Wifi Bulb's history:
Became unavailable triggered by automation HASSIO Startup - Devices Off and On triggered by event 'timer.finished'
8:08:28 AM - 18 minutes ago

Turned on
8:07:35 AM -  - 19 minutes ago

The other devices just remain as unavailable however they show correctly in eWelink App on Mobile (I have about 30 WiFi Bulbs, and only 3 of them behave like above, and these three are not behind a switch that controls the electrical flow to the bulbs),

**Comment by skubi23t** [comment]
> 

I have exactly the same issue after updating to 3.1.0
Is there any solution without removing everything?

**Comment by tammeryousef1006** [comment]
> > 
> 
> I have exactly the same issue after updating to 3.1.0 Is there any solution without removing everything?

change the password to the old one as of now , until alexxx find solution for this

**Comment by sator86** [comment]
Having exactly the same issue :(
asking me the password again and again, but when I enter my credentials, it's tell me that there were already registred 
@AlexxIT any help please :)

**Comment by joelhauxwell** [comment]
I'm having exactly the same problem

**Comment by NMichas** [comment]
Same here :(

**Comment by AlexxIT** [comment]
I have checked the password change on the latest version of the integration. Everything works as expected.
Create a new issue if the problem is still relevant.
