### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by pdaccache** [AlexxIT/SonoffLAN#901]
In hassio device status not always syncing so if the device is offline or unavailable it is still online in hassio what can be done to force status update?

**Comment by SirDester** [comment]
Duplicated, already reported in #897

**Comment by SirDester** [comment]
I have the same issue, two smart bulbs are behind a switch and when I turn off the main switch the two bulbs continue to appear as "online" to hassio. The only way to refresh their state is try to switch them off manually, and they become unavaiable (because the command timeout).

I tried with an automation connected to the main switch state change but it's not consistent (sometimes as you turn off main switch the bulbs receive commands successfully for a while even if they are already really unavailable, and so they dont change state to unavailable.... a mistery of WiFi and current...)

**Comment by donovanbell** [comment]
Same issue - seems to have occurred (for me at least) since the latest release of Home Assistant (22.7.1) - before that was working fine.

Basically all my Sonoff power monitors stop syncing - until I goto the eWLink smart home interface in HA - and refresh each device.
It then sync's for about a minute - and then stops again.

![image](https://user-images.githubusercontent.com/60425936/177981288-03c169ec-bc48-4ccf-88ee-c36aa86278b3.png)

**Comment by Smelkoff** [comment]
Same problem, after update HA. Dual R3 work fine ewelink app, but not sync status of switches in HA interface
<img width="351" alt="Screenshot 2022-07-08 at 20 54 55" src="https://user-images.githubusercontent.com/65180359/178045238-a343ccd6-0eab-4a44-a4a1-707c72601528.png">
.

**Comment by dluck21** [comment]
2022-07-09 20:35:44 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-09 20:35:44 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
 

dont work zigbee sensor and others lights  :(

**Comment by BigWalnutZ** [comment]
> Same issue - seems to have occurred (for me at least) since the latest release of Home Assistant (22.7.1) - before that was working fine.
> 
> Basically all my Sonoff power monitors stop syncing - until I goto the eWLink smart home interface in HA - and refresh each device. It then sync's for about a minute - and then stops again.
> 
> ![image](https://user-images.githubusercontent.com/60425936/177981288-03c169ec-bc48-4ccf-88ee-c36aa86278b3.png)

I have he same issue.  My Sonoff S31's are not showing power unless I open the app on my phone.  I have the following in my config:  
```sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  sensors: [temperature, humidity, power, current, voltage]
  force_update: [temperature, humidity, power, current, voltage]
  scan_interval: "00:01:00" # (optional) default 5 minutes
  reload: always # update device list every time HA starts
  #sensors: [temperature, humidity, sw_version, cloud, rssi, local, unit_of_measurement ]
```

**Comment by whalik** [comment]
> 

Few of my switches act this way sometimes.

**Comment by donovanbell** [comment]
I seem to have sorted the issue out that I was having with values / status' not syncing

In my case - I have the Sonoff integration and eWeLink add-on installed.

I found if I disabled the eWeLink add-on - the problem is resolved now - my Sonoff devices are syncronising again - 
![image](https://user-images.githubusercontent.com/60425936/182554602-79b1c259-7e63-4b9c-a7f8-a9f679bce22f.png)

**Comment by dezza** [comment]
I think its hardcoded honestly. It seems as if only Sonoff cloud can trigger the forced update and all other attempts delivers "old data"

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
